### ISSUE TITLE
Browser extension to show/toggle Xdebug cookie status

### ISSUE THREAD

**Issue by philipnewcomer** [Pilothouse-App/pilothouse#22]
Create a Chrome extension (and possibly for other browsers as well) to show and toggle the current status of the Xdebug cookie

**Comment by Jaace** [comment]
I've written a small Chrome Extension to handle this. Since this doesn't exist in the Chrome Web Store (not sure how to go about doing that) I wanted to deliver it here, with a README on how to set it up, which requires turning developer mode on in Chrome and loading the unpacked extension via chrome://extensions/ - pretty straight-forward.

I want to get your preference on this before I do anything; it's a pretty small piece of code, a few files. I could include it in a directory in this repo or deliver separately. Let me know either way

**Comment by philipnewcomer** [comment]
That's awesome, thanks @Jaace!

I'd love for this to be on the Chrome web store eventually, but I'd like to have us test it for a bit first. 

I've created [a new repo](https://github.com/Pilothouse-App/pilothouse-chrome-extension) here in the Pilothouse org for the Chrome extension, and added you @Jaace as a collaborator. Go ahead and push to that.

I'm going to close this issue now that we have a dedicated repo for the Chrome extension, and we can continue discussion about the extension there.

https://github.com/Pilothouse-App/pilothouse-chrome-extension
