### ISSUE TITLE
Make sweet logo for Pilothouse :)

### ISSUE THREAD

**Issue by AaronHolbrook** [Pilothouse-App/Pilothouse#44]

**Comment by philipnewcomer** [comment]
I'm thinking something to indicate coding, along with the Docker whale. Maybe something like this, replacing the whale emoji with something more Docker-like: <🐳>

(Not sure what parts of the Docker logo we can use due to copyright issues.)

**Comment by AaronHolbrook** [comment]
Or the docker name for that matter?

**Comment by philipnewcomer** [comment]
If using the Docker name becomes an issue, I'd probably rename the project to `dckrbx` or some permutation of that, kind of the WordPress foundation allows you to use `WP` in your name but not `WordPress`.

**Comment by briansaycocie** [comment]
Docker is an open source project right? I feel like its possible to use the name and a version of the whale. May need to check a bit more on that though.

**Comment by philipnewcomer** [comment]
Looks like the Docker project itself is licensed under the Apache 2.0 license. Not sure if the artwork falls under that umbrella or not.

**Comment by Jaace** [comment]
https://www.docker.com/brand-guidelines

Some reading on the matter - not sure if the name also needs to be modified due to this. It may be worth reaching out to them regarding both the image and name, though for the image it looks like you'd need to at least make it different enough that it wouldn't be confused for an officially licensed Docker product -- `DO NOT: [...] Modify the Docker logo in any other way than scaling it`

**Comment by philipnewcomer** [comment]
Thanks for finding that @Jaace!

Looks like the name "DockerBox" is not allowed under those guidelines (emphasis mine):

> DO NOT... Use the word Docker as the first word in the name of your website or domain name, ***application*** or product...

Guess we need to [rename the project again](https://github.com/DockerBox/dockerbox/issues/30) (sigh).

We could just do something like `dckrbox`, but I don't really like that and I'm open to other suggestions.

**Comment by AaronHolbrook** [comment]
Plus dckrbox, at first glance looks like something a little more profane

**Comment by briansaycocie** [comment]
Possible project names (off the top of my head):
- Boxy
- Stacked
- ModularBox or ModBox
- StackedBox
- BuildBox
- BoxUp
- BoxLab
- CrateLab
- WireCrate

**Comment by AaronHolbrook** [comment]
DevBox?

**Comment by philipnewcomer** [comment]
I like the name DevBox but that's already being used for other local environment projects:
https://www.predix.io/services/other-resources/devbox.html
https://github.com/Aboalarm/devbox

Doesn't necessary mean we can't use it too, though, if it's not copyrighted

**Comment by Jaace** [comment]
Docker is a synonym for "longshoreman" so you could possibly go the route of that terminology (nautical/container/shipping) just an idea though :)

**Comment by Jaace** [comment]
* DevPilot
* StowBox
* DevPack
* DevStash
or combinations therein haha

**Comment by philipnewcomer** [comment]
I've settled on a new name for the project: _Pilothouse_. This is a nautical term (thanks for the suggestion, @Jaace), which fits well with the concept of being the control center for a "ship" of docker containers.

I considered using "Wheelhouse" instead of "Pilothouse", as I think wheelhouse may be slightly more recognizable for what it is, but Wheelhouse is already a [well-established brand](http://www.wheelhouse.com/), and I want to avoid any potential legal issues there.

Since the `pilothouse` GitHub username was already taken, I'm going to be naming the GitHub organization `Pilothouse-App`. I think this project could definitely be called an app, and I wouldn't rule out a GUI down the road which would make the app suffix even more appropriate.

I will be renaming the GitHub organization and repo momentarily.

**Comment by philipnewcomer** [comment]
Project has been fully renamed throughout the codebase. Note that just pulling down the latest changes will cause you to loose your mysql databases. I have put together a set of instructions for backing up and restoring your mysql data: https://github.com/Pilothouse-App/pilothouse/wiki/Upgrading-from-DockerBox-to-Pilothouse

**Comment by AaronHolbrook** [comment]
Still need a sweet logo for this :)

**Comment by philipnewcomer** [comment]
> Still need a sweet logo for this :)

ping @briansaycocie 😃

**Comment by briansaycocie** [comment]
I'm working on this!

**Comment by briansaycocie** [comment]
![pilothouse](https://cloud.githubusercontent.com/assets/1328262/26376634/d589a12c-3fd2-11e7-8c8b-0ae256b674ab.png)

Yay or nay? I can add some colors to it. Thoughts on a color palette?

**Comment by philipnewcomer** [comment]
I think this is a good start. I'd like to see a simpler version of the ship with fewer individual shapes making up the icon. The reason being that the ship icon will in some cases be displayed at a small size, so it needs to be something that works as a favicon, or as a small icon on a non-Retina display. For instance, the GitHub organization icon on a user's profile page is 35x35px.

As for a color palette, I think a monochromatic color scheme would work well here. I personally like blue, but more importantly, I think blue would be appropriate because the project name has a nautical theme. I know, ships themselves aren't generally blue, but neither are whales (they're gray) and Docker's whale icon is a light blue. I like subtle gradients too. Maybe try a darkish unsaturated blue (#263858 looks nice on my display) and its monochromatic variations? Or #263858 combined with a dark gray or black.

Does that make sense?

**Comment by philipnewcomer** [comment]
I want to get this wrapped up so I decided to just use a fairly simple icon of a ship's wheel. I found a GPL-licensed icon at https://www.iconfinder.com/icons/1054980/steering_wheel_wheel_icon, which I tweaked just a bit, so that's what I'm going to be using, along with the text "Pilothouse" in Merriweather:

![logo](https://user-images.githubusercontent.com/1446874/28695589-135a3ff8-72fe-11e7-9ae9-27107b905efa.png)
