### ISSUE TITLE
Change db creds away from wordpress

### ISSUE THREAD

**Issue by AaronHolbrook** [Pilothouse-App/pilothouse#64]
I think the general sense here is that this is no longer just a `wordpress` development system.

It's minor, but I think the database user/pass should reflect that attitude.

**Comment by AaronHolbrook** [comment]
https://github.com/Pilothouse-App/pilothouse/wiki/Connecting-to-a-Site's-Database-Remotely

**Comment by AaronHolbrook** [comment]
maybe something like `pilothouse` /`pilothouse`

**Comment by philipnewcomer** [comment]
Yep, I agree the creds should not be WordPress-specific. However, I don't think we can change this without breaking existing installs which were created with the old credentials, unless we maintain two sets of credentials (`wordpress` / `wordpress` and `pilothouse` / `pilothouse`). I wouldn't be opposed to doing that for the time being, since the project is still considered in "beta" status, but the goal should be to transition to just `pilothouse` / `pilothouse` for the long term, maybe in a 1.0 release.

**Comment by philipnewcomer** [comment]
This actually isn't a breaking change; anyone who's already using Pilothouse will have a MySQL user already created with the necessary permissions for `wordpress`/`wordpress`, and that won't change by setting a new default user for new sites.

Wiki updated.

**Comment by AaronHolbrook** [comment]
https://github.com/Pilothouse-App/pilothouse/wiki/Connecting-to-a-Site's-Database-Remotely

**Comment by AaronHolbrook** [comment]
FYI for anyone coming after, the new creds are now `pilothouse/pilothouse`
