### ISSUE TITLE
Allow tailing of different types of logs

### ISSUE THREAD

**Issue by AaronHolbrook** [Pilothouse-App/Pilothouse#67]
I.e. we can tail all `nginx` logs, but it's all combined (access and error).

Would be helpful to be able to specify what logs we'd like to see, i.e.:

```
pilothouse logs nginx error
```

to watch just the error logs

**Comment by philipnewcomer** [comment]
This isn't something that the [docker logs](https://docs.docker.com/engine/reference/commandline/logs/) facility currently provides the ability to do. Closing for now due to lack of required support in Docker, but would definitely reexamine if Docker added the required support to request only logs of a certain type.
